@startuml

header OAuth 2.0
footer Page %page% of %lastpage%

title Client Credentials grant
autonumber

participant Authorization Server
participant System A
participant System B

System A -> Authorization Server : Token request\n<font color=orange>[POST]</font>/as/oauth2/token\n?grant_type=client_credentials\n&scope=system_b.resource.verb\nHeader:Authorization:Basic B64(<font color=red>system_a</font>:<font color=red>$CLIENT_SECRET</font>)
AuthorizationServer -> System A : <font color=green>200 OK</font> \n Body: \n{\n\t"access_token":"<font color=red>$AT</font>",\n\tscope":"system_b.resource.verb",\n\t"token_type":"Bearer",\n\t"expires_in":<font color=red>$AT_LIFETIME</font>\n}

System A -> System B : API Call \n<font color=orange>[VERB]</font> /b/api/resource\n Header: Authorization: Bearer <font color=red>$AT</font>
System B -> System A : API Response
@enduml
