@startuml

header OAuth 2.0
footer Page %page% of %lastpage%

title Client Credentials Grant
autonumber

participant Auth as "Authorization Server"
participant 1 as "System 1"
participant 2 as "System 2"

1 -> Auth : **Token request**\n<font color=orange>[POST]</font>https://as.example.com/oauth2/token\n?grant_type=client_credentials\n&scope=https%3A%2F%2Fsystem2.example.com%2Fapi%2Fresource.verb\nHeader:Authorization:Basic B64(system1:<font color=red>$CLIENT_SECRET</font>)
Auth -> 1 : <font color=green>200 OK</font> \n Body: \n{\n\t"access_token":"<font color=red>$AT</font>",\n\t"scope":"https://system2.example.com/api/resource.verb",\n\t"token_type":"Bearer",\n\t"expires_in":<font color=red>$AT_LIFETIME</font>\n}

1 -> 2 : **API Call** \n<font color=orange>[VERB]</font>https://system2.example.com/api/resource\n Header: Authorization: Bearer <font color=red>$AT</font>
2 -> 1 : **API Response**
@enduml
