@startuml

header OAuth 2.0
footer Page %page% of %lastpage%

title Client Credentials gant
autonumber

SystemA -> AS : Token request\n<font color=orange>[POST]</font>/as/oauth2/token\n?grant_type=client_credentials\n&scope=<font color=red>$SCOPES</font>\nHeader:Authorization:Basic B64 <font color=red>$CLIENT_ID</font>:<font color=red>$CLIENT_SECRET</font>
AS -> SystemA : <font color=green>200 OK</font> \n Body: \n{\n\t"access_token":"<font color=red>$AT</font>",\n\tscope":"<font color=red>$SCOPES</font>",\n\t"token_type":"Bearer",\n\t"expires_in":<font color=red>$AT_LIFETIME</font>\n}

SystemA -> SystemB : API Call \n<font color=orange>[VERB]</font> /b/api/action\n Header: Authorization: Bearer <font color=red>$AT</font>
SystemB -> SystemA : API Response
@enduml
