name: Generate PlantUML Diagrams
on:
  workflow_dispatch:
    paths:
      - '**.plantuml'
    branches:
      - main
jobs:
  ci:
    runs-on: ubuntu-latest
    env:
        UML_FILES: ".plantuml"
    steps:
      - name: Checkout Source 
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get changed UML files
        id: getfile
        run: |
          echo "::set-output name=files::$(git diff-tree -r --no-commit-id --name-only ${{ github.sha }} | grep ${{ env.UML_FILES }} | xargs)"
      - name: UML files considered echo output
        run: |
          echo ${{ steps.getfile.outputs.files }}
      - name: Generate PNG Diagrams
        uses: cloudbees/plantuml-github-action@master
        with:
            args: -v -tpng ${{ steps.getfile.outputs.files }}
      - name: Push Local Changes
        uses:  stefanzweifel/git-auto-commit-action@v4.1.2 
        with: 
          commit_user_name: "GitHub Actions"
          commit_user_email: "action@kamereon.org"
          commit_author: "GitHub Actions <action@henrilefevrepro.github.com>"
          commit_message: "[GitHub Actions] Generate PNG images for PlantUML diagrams" 
          branch: ${{ github.head_ref }}
